DROP DATABASE IF EXISTS `vmx`;
CREATE DATABASE `vmx`;
USE `vmx`;

CREATE TABLE `users`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `role` ENUM('student', 'admin') NOT NULL DEFAULT 'student',
    -- `status` BOOLEAN NOT NULL DEFAULT '1',
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `categories` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
    `image` TEXT NOT NULL,
    `published` BOOLEAN NOT NULL DEFAULT '0',
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `courses`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `category` INT UNSIGNED NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
    `image` TEXT NOT NULL,
    `level` ENUM('all', 'beginner', 'intermediate', 'expert') NOT NULL DEFAULT 'all',
    `pricing` ENUM('free', 'paid') NOT NULL DEFAULT 'free',
    `published` BOOLEAN NOT NULL DEFAULT '0',
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(`category`) REFERENCES `categories`(`id`) ON DELETE CASCADE
);

CREATE TABLE `sections`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `course` INT UNSIGNED NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `order` TINYINT UNSIGNED NOT NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(`course`) REFERENCES `courses`(`id`) ON DELETE CASCADE
);

CREATE TABLE `lessons`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `section` INT UNSIGNED NOT NULL,
    `preview` BOOLEAN NOT NULL DEFAULT '0',
    `title` TEXT NOT NULL,
    `url` TEXT NOT NULL,
    `order` TINYINT UNSIGNED NOT NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(`section`) REFERENCES `sections`(`id`) ON DELETE CASCADE
);

CREATE TABLE `enrollments`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user` INT UNSIGNED NOT NULL,
    `course` INT UNSIGNED NOT NULL,
    `payment` INT UNSIGNED NOT NULL,
    `createdAt` DATETIME NOT NULL,
    `updatedAt` DATETIME NOT NULL,
    FOREIGN KEY(`user`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY(`course`) REFERENCES `courses`(`id`) ON DELETE CASCADE
);

CREATE TABLE `payments`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `enrollment` INT UNSIGNED NOT NULL,
    `method` ENUM('none', 'card') NOT NULL DEFAULT 'none',
    `amount` INT UNSIGNED NOT NULL DEFAULT '0',
    `transaction` INT UNSIGNED DEFAULT NULL,
    `status` BOOLEAN NOT NULL DEFAULT '1',
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`enrollment`) REFERENCES `enrollments`(`id`) ON DELETE CASCADE
);
